DROP TABLE IF EXISTS reserve;
DROP TABLE IF EXISTS post;

CREATE TABLE reserve (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user TEXT NOT NULL,
  room INTEGER NOT NULL,
  date_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);